const KEY='dim-utilities-v1';
const icons={'Електроенергія':'⚡','Холодна вода':'💧','Гаряча вода':'♨️','Газ':'🔥','Опалення':'☀️','Вивіз сміття':'♻️','Інтернет':'⌁','Квартплата':'⌂'};
const defaults=[{name:'Електроенергія',unit:'кВт·год',meter:true,tariff:4.32},{name:'Холодна вода',unit:'м³',meter:true,tariff:30.38},{name:'Газ',unit:'м³',meter:true,tariff:7.96},{name:'Опалення',unit:'м²',meter:false,tariff:38.5},{name:'Вивіз сміття',unit:'міс.',meter:false,tariff:45}];
const $=s=>document.querySelector(s), monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`, money=n=>Number(n||0).toLocaleString('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2}), fmtMonth=k=>{let [y,m]=k.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('uk-UA',{month:'long',year:'numeric'})};
function fresh(){return {apartments:[{id:crypto.randomUUID(),name:'Квартира 1',services:defaults.map((s,i)=>({...s,id:crypto.randomUUID(),previous:0,current:0,selected:i<3}))}],records:{},active:null,period:monthKey(new Date())}}
let db;try{db=JSON.parse(localStorage.getItem(KEY))||fresh()}catch{db=fresh()}if(!db.apartments?.length)db=fresh();db.active=db.apartments.some(a=>a.id===db.active)?db.active:db.apartments[0].id;
const apt=()=>db.apartments.find(a=>a.id===db.active);function persist(){localStorage.setItem(KEY,JSON.stringify(db))}
function recKey(){return `${db.active}_${db.period}`}
function carryPrevious(){let a=apt(),prev=new Date(+db.period.slice(0,4),+db.period.slice(5)-2,1),rec=db.records[`${db.active}_${monthKey(prev)}`];a.services.forEach(s=>{let match=rec?.services?.find(x=>x.id===s.id);if(match&&s.meter)s.previous=Number(match.current||0);});}
function calc(s){let q=s.meter?Math.max(0,(+s.current||0)-(+s.previous||0)):1;return q*(+s.tariff||0)}
function render(){const sel=$('#apartmentSelect');sel.innerHTML=db.apartments.map(a=>`<option value="${a.id}" ${a.id===db.active?'selected':''}>${esc(a.name)}</option>`).join('');$('#periodLabel').textContent=fmtMonth(db.period);let a=apt(),sum=a.services.reduce((n,s)=>n+calc(s),0);$('#grandTotal').innerHTML=`${money(sum)} <small>₴</small>`;$('#serviceCount').textContent=`За ${a.services.length} ${a.services.length===1?'послугу':'послуг'}`;
$('#serviceList').innerHTML=a.services.length?a.services.map(s=>serviceHtml(s)).join(''):`<div class="empty">Додайте першу послугу, щоб почати розрахунок.</div>`;
$('#selectionList').innerHTML=a.services.map(s=>`<label class="chip"><input type="checkbox" data-select="${s.id}" ${s.selected?'checked':''}>${esc(s.name)}</label>`).join('')||'<span class="muted small">Поки немає послуг</span>';
$('#selectedTotal').textContent=`${money(a.services.filter(s=>s.selected).reduce((n,s)=>n+calc(s),0))} ₴`;renderHistory()}
function serviceHtml(s){let q=s.meter?Math.max(0,(+s.current||0)-(+s.previous||0)):1;return `<article class="service-card" data-id="${s.id}"><div class="service-top"><div class="service-name-wrap"><span class="service-icon">${icons[s.name]||'◉'}</span><div><div class="service-name">${esc(s.name)}</div><div class="service-caption">${s.meter?`${money(q)} ${esc(s.unit)} спожито`:'Фіксоване нарахування'}</div></div></div><div style="display:flex;gap:9px;align-items:flex-start"><div class="service-cost">${money(calc(s))} ₴<small>${money(s.tariff)} ₴ / ${esc(s.unit)}</small></div><button class="more-button" data-edit="${s.id}" aria-label="Налаштувати ${esc(s.name)}">···</button></div></div><div class="meter-fields">${s.meter?`<div class="field"><label>Попередній показник</label><input type="number" step="any" data-prop="previous" value="${val(s.previous)}" aria-label="Попередній показник"></div><div class="field"><label>Поточний показник</label><input type="number" step="any" data-prop="current" value="${val(s.current)}" aria-label="Поточний показник"></div>`:`<div class="field"><label>Нарахування</label><input type="number" value="1" readonly></div>`}<div class="field"><label>Тариф · ₴/${esc(s.unit)}</label><input type="number" min="0" step="any" data-prop="tariff" value="${val(s.tariff)}" aria-label="Тариф"></div></div>${s.meter?`<div class="unit-hint">Попередній показник підставляється з минулого місяця. За потреби його можна змінити.</div>`:''}</article>`}
function renderHistory(){let rows=Object.entries(db.records).filter(([k])=>k.startsWith(db.active+'_')).sort(([a],[b])=>b.localeCompare(a));$('#historyList').innerHTML=rows.length?rows.map(([k,r])=>`<div class="history-item"><div><strong>${fmtMonth(k.split('_').at(-1))}</strong><span>${r.services.length} послуг · збережено</span></div><b>${money(r.total)} ₴</b><button data-record="${k}">Переглянути</button></div>`).join(''):'<div class="empty">Збережені місяці з’являться тут.</div>'}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const val=x=>String(x??'').replace(/"/g,'&quot;');
function refreshCard(el){let s=apt().services.find(x=>x.id===el.dataset.id);if(!s)return;el.outerHTML=serviceHtml(s);$('#grandTotal').innerHTML=`${money(apt().services.reduce((n,x)=>n+calc(x),0))} <small>₴</small>`;$('#selectedTotal').textContent=`${money(apt().services.filter(x=>x.selected).reduce((n,x)=>n+calc(x),0))} ₴`}
const dlg=$('#modal');function modal(title,html,actions){$('#modalTitle').textContent=title;$('#modalContent').innerHTML=html;$('#modalActions').innerHTML=actions;dlg.showModal()}
function field(label,name,value,type='text',more=''){return `<div class="modal-field"><label>${label}</label><input name="${name}" type="${type}" value="${val(value)}" ${more} required></div>`}
function saveMonth(){const a=apt(),list=a.services.map(s=>({...s})),total=list.reduce((n,s)=>n+calc(s),0);db.records[recKey()]={apartment:a.name,period:db.period,total,services:list,savedAt:new Date().toISOString()};persist();render();}
$('#apartmentSelect').onchange=e=>{db.active=e.target.value;carryPrevious();persist();render()};$('#prevMonth').onclick=()=>moveMonth(-1);$('#nextMonth').onclick=()=>moveMonth(1);function moveMonth(d){let [y,m]=db.period.split('-').map(Number),x=new Date(y,m-1+d,1);db.period=monthKey(x);carryPrevious();persist();render()}
$('#serviceList').addEventListener('input',e=>{let card=e.target.closest('.service-card'),p=e.target.dataset.prop;if(!card||!p)return;let s=apt().services.find(x=>x.id===card.dataset.id);s[p]=e.target.value===''?'':Number(e.target.value);persist();refreshCard(card)});
$('#serviceList').addEventListener('click',e=>{let id=e.target.dataset.edit;if(id)editService(id)});$('#selectionList').onchange=e=>{let id=e.target.dataset.select,s=apt().services.find(x=>x.id===id);if(s){s.selected=e.target.checked;persist();render()}};
$('#selectAll').onclick=()=>{let services=apt().services,all=services.every(s=>s.selected);services.forEach(s=>s.selected=!all);persist();render()};$('#addService').onclick=$('#navAdd').onclick=()=>addService();$('#addApartment').onclick=addApartment;$('#saveMonth').onclick=()=>{saveMonth();modal('Місяць збережено','<p>Нарахування за цей період додано до історії.</p>','<button class="primary-button" value="ok">Готово</button>')};
function addApartment(){modal('Нова квартира',`<div class="modal-content-grid">${field('Назва квартири','name','Квартира '+(db.apartments.length+1))}</div>`,'<button class="secondary" value="cancel">Скасувати</button><button class="primary-button" value="save">Додати квартиру</button>');dlg.onclose=()=>{if(dlg.returnValue!=='save')return;let n=dlg.querySelector('[name=name]').value.trim();if(!n)return;let base=apt(),a={id:crypto.randomUUID(),name:n,services:base.services.map(s=>({...s,id:crypto.randomUUID(),previous:0,current:0}))};db.apartments.push(a);db.active=a.id;persist();render()}}
function addService(){modal('Нова послуга',`<div class="modal-content-grid">${field('Назва послуги','name','','text','placeholder="Наприклад, гаряча вода"')}${field('Одиниця виміру','unit','м³')}${field('Тариф, ₴','tariff','0','number','min="0" step="any"')}<div class="modal-field"><label>Облік</label><select name="meter"><option value="yes">За лічильником</option><option value="no">Фіксована сума</option></select></div></div>`,'<button class="secondary" value="cancel">Скасувати</button><button class="primary-button" value="save">Додати послугу</button>');dlg.onclose=()=>{if(dlg.returnValue!=='save')return;let f=dlg.querySelector('form'),name=f.querySelector('[name=name]').value.trim();if(!name)return;apt().services.push({id:crypto.randomUUID(),name,unit:f.querySelector('[name=unit]').value.trim()||'од.',tariff:+f.querySelector('[name=tariff]').value,meter:f.querySelector('[name=meter]').value==='yes',previous:0,current:0,selected:true});persist();render()}}
function editService(id){let s=apt().services.find(x=>x.id===id);modal('Налаштування послуги',`<div class="modal-content-grid">${field('Назва','name',s.name)}${field('Одиниця виміру','unit',s.unit)}${field('Тариф, ₴','tariff',s.tariff,'number','min="0" step="any"')}<div class="modal-field"><label>Облік</label><select name="meter"><option value="yes" ${s.meter?'selected':''}>За лічильником</option><option value="no" ${!s.meter?'selected':''}>Фіксована сума</option></select></div></div>`,'<button class="danger" value="delete">Видалити</button><span style="flex:1"></span><button class="secondary" value="cancel">Скасувати</button><button class="primary-button" value="save">Зберегти</button>');dlg.onclose=()=>{if(dlg.returnValue==='delete')apt().services=apt().services.filter(x=>x.id!==id);else if(dlg.returnValue==='save'){let f=dlg.querySelector('form');s.name=f.querySelector('[name=name]').value.trim()||s.name;s.unit=f.querySelector('[name=unit]').value.trim()||s.unit;s.tariff=+f.querySelector('[name=tariff]').value;s.meter=f.querySelector('[name=meter]').value==='yes'}persist();render()}}
$('#historyList').addEventListener('click',e=>{let k=e.target.dataset.record;if(!k)return;let r=db.records[k];modal(fmtMonth(r.period),`<div>${r.services.map(s=>`<div class="history-detail"><span>${esc(s.name)}</span><strong>${money(calc(s))} ₴</strong></div>`).join('')}<div class="selection-total"><span>Разом</span><strong>${money(r.total)} ₴</strong></div></div>`,'<button class="secondary" value="close">Закрити</button><button class="primary-button" id="loadRecord" value="load">Відкрити місяць</button>');dlg.onclose=()=>{if(dlg.returnValue==='load'){db.period=r.period;carryPrevious();persist();render()}}});
$('#settingsBtn').onclick=()=>modal('Ваші дані',`<div class="modal-menu"><button id="exportData">Скопіювати резервну копію</button><button id="importData">Відновити з копії</button><button id="resetData">Очистити всі дані</button><input id="importFile" type="file" accept="application/json" hidden></div><p class="modal-note">Нарахування зберігаються у пам’яті браузера на цьому пристрої. Резервна копія допоможе перенести їх на інший пристрій.</p>`,'<button class="secondary" value="close">Закрити</button>');$('#modalContent').onclick=e=>{if(e.target.id==='exportData'){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='komunalni-vytraty-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}if(e.target.id==='importData')$('#importFile').click();if(e.target.id==='resetData'){if(confirm('Видалити всі квартири, тарифи та історію?')){db=fresh();persist();render();dlg.close()}}};$('#importFile').onchange=async e=>{try{let next=JSON.parse(await e.target.files[0].text());if(!next.apartments||!next.records)throw Error();db=next;db.active=db.apartments[0].id;persist();render();dlg.close()}catch{alert('Не вдалося прочитати файл копії.')}}};
if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));persist();render();
